version: '3.7'
services:
  app:
    build: ./Frontend
    ports:
      - 3000:3000
    environment:
      NODE_ENV: "project"
      SERVER_URL: "localhost"
      SERVER_PORT: "3002"
    links:
      - server
  server:
    build: ./Backend
    links:
      - db
    ports:
      - 5000:5000
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  db:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - BACKEND_PORT=${BACKEND_PORT}
      - ALLOW_HOSTS=web

